server:
  port: 8090
  servlet:
    context-path: /hotel-system/api

spring:
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}


jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
