server:
  port: 8090
  servlet:
    context-path: /hotel-system/api

spring:
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}


jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html